{% set name = "pytest-unordered" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-unordered-{{ version }}.tar.gz
  sha256: 8187e6d68a7d54e5447e88c229cbeafa38205e55baf7da7ae57cc965c1ecdbb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pytest >=6.0.0
    - python >=3.7

test:
  imports:
    - pytest_unordered
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/utapyngo/pytest-unordered
  summary: Test equality of unordered collections in pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
