{% set name = "pytest-unordered" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f953a438db00a9f6f99a0f4727f2d75e72dd93319b3d548a97ec9db4903a44f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pytest >=6.0.0
    - python >={{ python_min }}

test:
  imports:
    - pytest_unordered
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/utapyngo/pytest-unordered
  summary: Test equality of unordered collections in pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
