{% set name = "pytest-unordered" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-unordered-{{ version }}.tar.gz
  sha256: f61b4f6e06a60a92db50968954efac93e2f584290a49f53ad135e3f32f57e02a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pytest >=6.0.0
    - python >=3.7

test:
  imports:
    - pytest_unordered
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/utapyngo/pytest-unordered
  summary: Test equality of unordered collections in pytest
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - asford
